### ISSUE TITLE
Nice ,But cant not automatic shoot Plz help me .

### ISSUE THREAD

**Issue by ra22122123** [kingsollyu/logitech-pubg#1]
First ，Thanks for offering. I going back to customary project and according to the instructions setting my computer ,and i turn off system UAC permission .  i'm not change mouse DPI and fire key in game (because set fire key PAUSE can not shoot ..) , but  unfortunaly however i can automatic shoot any gun in customary project  . so  how to automatic shoot  in game  .just like M16a4 ,this gun can not  change fire mode to automatic , maybe this script only cannot be run in automatic mode？ 
Finally .Thanks for offering .thank you. 

首先感谢您提供这么好的东西，我有点问题想问一下，我想让M16a4连发，那就必须让M16a4 切换成单发模式。但是我试了很多次都不行，我还参照基于原来的脚本的说明看了下，但是我没改射击按键和灵敏度，关闭了系统的UAC。还是不行，同样我又试了一下原来作者的脚本 ，可以全自动射击。请问这是什么原因？或者，我哪部做错了呢？出个稍微详细点的说明吧。 谢谢，再次感谢作者的提供。

**Comment by kingsollyu** [comment]
这个我也在看，昨天晚上测试了一下，最新的代码还没有推送，差不多是这样写的有点作用
```lua
-------------------------------------------------------------------------------
-- 选择M16A4枪
-------------------------------------------------------------------------------
pubg.onWeaponM16a4 = function ()
	local weaponRocilData  = {5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 2, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5}
	local weaponDuration   = 20
	local currentRecoilPos = 1
	repeat
		MoveMouseRelative(pubg.random(-1,2), weaponRocilData[currentRecoilPos])
		currentRecoilPos = currentRecoilPos + 1
		Sleep(weaponDuration)
		OutputLogMessage(tostring(currentRecoilPos) .. " ")
		if currentRecoilPos == #weaponRocilData then
			currentRecoilPos = 1
		elseif currentRecoilPos % 5 == 0 then
			ReleaseMouseButton(1)
			Sleep(10)
			PressMouseButton(1)
			Sleep(100)
		end
	until not IsMouseButtonPressed(1)
	OutputLogMessage("IsMouseButtonPressed == false\n")
end

```

**Comment by ra22122123** [comment]
我建议所有的武器都用单发模式而不是全自动，所有武器自动连点，因为这样会兼容更多的配件情况  比如手枪。

**Comment by kingsollyu** [comment]
单发的，你不感觉太假了吗？难道是我多想了？
