### ISSUE TITLE
没有必要一个枪写一个函数吧

### ISSUE THREAD

**Issue by zyxbcde** [kingsollyu/logitech-pubg#3]
因为压枪数据只有下移的量不一样，完全可以把这个下移量定义为一个变量，跟鼠标的键一一对应行了，能少写不少if else。

**Comment by kingsollyu** [comment]
当时想的比较多，枪械的数据什么的，到后来改过来改过去，发现枪械数据完全用不到来，但是这些函数就遗留下来了。
